# Server Port
server:
    port: 8080

# database Local, Docker Environment Variable
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/db_springproject?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true}
        username: ${SPRING_DATASOURCE_USERNAME:user_springProject}
        password: ${SPRING_DATASOURCE_PASSWORD:1234}
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        cache: false

# spring data jpa Setting
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: update
# File Path Local, Docker variable
app:
    upload-dir: ${APP_UPLOAD_DIR:./upload/board_images/}
    img-dir: ${APP_IMG_DIR:./upload/attraction_img/}
    sql:
        local: ${APP_IS_LOCAL:yes}
        filepath: ${APP_SQL_FILE_PATH:file:data/insert_data.sql}